### ISSUE TITLE
error in Modify protocol Fields 

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#101]
Al querer modificar los parámetros definidos en un protocolo, se generan varios errores:

1- en la función handling_protocols.py la línea 
   p_fields['sample_protocol_id'] = sample_project_obj
 se debe sustituir por:
   p_fields['protocol_id'] = protocol_obj

2- Los campos que tiene la función create_protocol_parameter no coinciden con los parámetros que tiene la función definida:

![image](https://user-images.githubusercontent.com/76442429/169100987-5c9ed0ee-a819-42a8-b3c0-38c3fab24f18.png)

![image](https://user-images.githubusercontent.com/76442429/169100291-c29298bd-dc13-4610-9ace-1ec1e6718577.png)

**Comment by luissian** [comment]
Second error was because the key of  "Parameter name" was not defined.  "Field name" which  it was in code was wrong and must be "Parameter name".
Change in code is:
"p_fields["Parameter name"] = row_data[1]

Implementation  in commit e3882a557d6cf5bcaaacf5fab87b069979b5f2b2
Pending for confirmation solved to close
