### ISSUE TITLE
User can't search service/project by sample name

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#264]
### Description of the bug

# User can't search service/project by sample name

When logged to a normal user (not admin user), if you try to search a service or a project by sample name, it doesn't allow you to search it. It does work with admin users.

## With bioinfoadm:
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/83209377-2a6b-44ca-bbb2-86b055871159)
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/e821d478-5207-4580-acc5-42e6703169f6)
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/0b4b9200-f61b-4a4d-8b5d-532f14338e9e)

## With the service's/project's user:
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/fa5b74c9-d3d4-4fb4-a7c6-b523164c8913)
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/cbe26476-a9a0-4a53-b12e-97f7962629b6)
![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/6b903008-09db-4fe8-94ce-881469c5d9e7)

**Comment by luissian** [comment]
When a normal user is searching for a service, only the user name must be filled with the user name. The field assigned user should be empty and in read mode. Because this field filter by the bioinformatic that was handled the service, and should be not showed for normal user. This is the reason why user does not get any service requested.

The last part of the issue seams to be that the sample is not assigned to user. It requests deep investigation with the real data
