### ISSUE TITLE
Error in url for sample_sheet and library kit file download.

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#3]
Can't download sample_sheet file in run information, and can't download library kit file for basespace in the upload new run form.

**Comment by luissian** [comment]
Hi. 
The issue is because the different user that CentOS and Ubuntu are using for Apache user.
The fastest way (becuase you are using the VM) is to allow write permissions to  anyone
go to 
cd /srv/iSkyLIMS/documents/wetlab
and set the write permisions for the following folders:
sudo chmod 777 BaseSpaceMigrationFiles/
sudo chmod 777 images_plot/
sudo chmod 777 library_kits/
sudo chmod 777 SampleSheets/
sudo chmod 777 tmp/
Rember that for ubuntu user, the passwd is "ubuntu01" 

Please test it and tell me if it works
